# Generated by Django 4.2.6 on 2023-10-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
